// Generated by CoffeeScript 1.7.1
(function() {
  var bar;

  bar = function() {
    return console.log("bar");
  };

}).call(this);

// Generated by CoffeeScript 1.7.1
(function() {
  var foo;

  foo = function() {
    alert("HEY");
    return console.log("foo");
  };

}).call(this);
